services:
  # FastAPI server instances
  fastapi-server:
    build: .
    ports:
      - "8000"  # Only needed for one instance to access docs, etc.
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - REDIS_HOST=redis
    deploy:
      replicas: 3  # Number of FastAPI instances to run
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    depends_on:
      - redis

  # Nginx load balancer
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Map the custom Nginx config file
    depends_on:
      - fastapi-server

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - default